const canvas = document.getElementById("canvas");
canvas.width = 2000;
canvas.height = 1000;
const stage = new createjs.Stage(canvas);
var text = new createjs.Text("Let's Add Integers", "100px Arial", "#ff7700");
text.x = 100;
text.y = 120;
text.textBaseline = "alphabetic";
stage.addChild(text);
stage.update();
